default_model: openai.gpt-4o-mini

generic:
  base_url: "http://localhost:11434/v1"

logger:
  level: info
  type: console
  path: ./logs/sqlporter.log
  progress_display: true
  show_chat: true
  show_tools: true
  truncate_tools: true

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]

sqlporter:
  models:
    converter_1: "generic.gemma3:4b"
    converter_2: "generic.llama3.2:1b"
    converter_3: "openai.gpt-4o-mini"

  paths:
    input_dir: "./my_input"
    output_dir: "./my_output"
    report_dir: "./my_reports"
    
  instructions:
    converter_1: ""
    converter_2: |
      Convert the Oracle SQL to PostgreSQL using Llama3-specific syntax rules.
      Respond ONLY with JSON as described in the default instruction.
    converter_3: ""

  settings:
    max_refinements: 3
    min_rating: "EXCELLENT"
    retry_limit: 3
    comment_prefix: "--"
    max_tokens: 10000
